import type { BankCatalogEntry, PaymentGateway, Transaction } from '../../types/payment';
import { DEFAULT_MIN_DEPOSIT_VND } from '../../types/payment';
import { getDefaultTiersForCurrency } from '../../services/depositPromotion';

const gatewayDefaults = {
  providerType: 'bank' as const,
  minDepositAmount: DEFAULT_MIN_DEPOSIT_VND,
  minDepositCurrency: 'VND' as const,
  depositNote: '',
  accountNumber: '1023456789',
  accountHolder: 'TAPHOAMMO VN',
  depositPromotionEnabled: true,
  depositPromotionTiers: getDefaultTiersForCurrency('VND'),
};

export const initialPaymentGateways: PaymentGateway[] = [
  {
    id: 'vcb',
    bankCode: 'VCB',
    bankName: 'Ngân hàng TMCP Ngoại thương Việt Nam',
    shortName: 'Vietcombank',
    color: '#006838',
    status: 'connected',
    environment: 'production',
    merchantId: 'TAPHOMMO_VCB_001',
    apiEndpoint: 'https://api.vietcombank.com.vn/payment/v2',
    webhookUrl: 'https://taphoammo.vn/api/webhook/vcb',
    lastSync: '17/05/2026 14:32',
    todayVolume: 45_200_000,
    enabled: true,
    ...gatewayDefaults,
    depositNote: 'Nội dung chuyển khoản phải ghi đúng mã đơn được hệ thống cấp.',
  },
  {
    id: 'tcb',
    bankCode: 'TCB',
    bankName: 'Ngân hàng TMCP Kỹ thương Việt Nam',
    shortName: 'Techcombank',
    color: '#ED1C24',
    status: 'connected',
    environment: 'production',
    merchantId: 'TAPHOMMO_TCB_001',
    apiEndpoint: 'https://api.techcombank.com.vn/gateway/v1',
    webhookUrl: 'https://taphoammo.vn/api/webhook/tcb',
    lastSync: '17/05/2026 14:28',
    todayVolume: 28_750_000,
    enabled: true,
    ...gatewayDefaults,
  },
  {
    id: 'mb',
    bankCode: 'MB',
    bankName: 'Ngân hàng TMCP Quân đội',
    shortName: 'MB Bank',
    color: '#5C2D91',
    status: 'connected',
    environment: 'sandbox',
    merchantId: 'TAPHOMMO_MB_SBX',
    apiEndpoint: 'https://sandbox.mbbank.com.vn/api/payment',
    webhookUrl: 'https://taphoammo.vn/api/webhook/mb',
    lastSync: '17/05/2026 13:55',
    todayVolume: 12_300_000,
    enabled: true,
    ...gatewayDefaults,
  },
  {
    id: 'acb',
    bankCode: 'ACB',
    bankName: 'Ngân hàng TMCP Á Châu',
    shortName: 'ACB',
    color: '#0054A6',
    status: 'disconnected',
    environment: 'sandbox',
    merchantId: '',
    apiEndpoint: 'https://sandbox.acb.com.vn/payment-api',
    webhookUrl: 'https://taphoammo.vn/api/webhook/acb',
    lastSync: '—',
    todayVolume: 0,
    enabled: false,
    ...gatewayDefaults,
  },
  {
    id: 'vtb',
    bankCode: 'VTB',
    bankName: 'Ngân hàng TMCP Công thương Việt Nam',
    shortName: 'VietinBank',
    color: '#005030',
    status: 'error',
    environment: 'production',
    merchantId: 'TAPHOMMO_VTB_001',
    apiEndpoint: 'https://api.vietinbank.vn/ipayment/v2',
    webhookUrl: 'https://taphoammo.vn/api/webhook/vtb',
    lastSync: '16/05/2026 22:10',
    todayVolume: 0,
    enabled: true,
    ...gatewayDefaults,
  },
  {
    id: 'bidv',
    bankCode: 'BIDV',
    bankName: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam',
    shortName: 'BIDV',
    color: '#006341',
    status: 'disconnected',
    environment: 'sandbox',
    merchantId: '',
    apiEndpoint: 'https://sandbox.bidv.com.vn/openapi/payment',
    webhookUrl: 'https://taphoammo.vn/api/webhook/bidv',
    lastSync: '—',
    todayVolume: 0,
    enabled: false,
    ...gatewayDefaults,
  },
];

export const BANK_CATALOG: BankCatalogEntry[] = [
  {
    id: 'vpb',
    bankCode: 'VPB',
    bankName: 'Ngân hàng TMCP Việt Nam Thịnh Vượng',
    shortName: 'VPBank',
    color: '#00A651',
    apiEndpoint: 'https://sandbox.vpbank.com.vn/api/payment',
    webhookUrl: 'https://taphoammo.vn/api/webhook/vpb',
    providerType: 'bank',
  },
  {
    id: 'tpb',
    bankCode: 'TPB',
    bankName: 'Ngân hàng TMCP Tiên Phong',
    shortName: 'TPBank',
    color: '#6B2C91',
    apiEndpoint: 'https://sandbox.tpbank.com.vn/payment/v1',
    webhookUrl: 'https://taphoammo.vn/api/webhook/tpb',
    providerType: 'bank',
  },
  {
    id: 'shb',
    bankCode: 'SHB',
    bankName: 'Ngân hàng TMCP Sài Gòn - Hà Nội',
    shortName: 'SHB',
    color: '#F7941D',
    apiEndpoint: 'https://api.shb.com.vn/payment',
    webhookUrl: 'https://taphoammo.vn/api/webhook/shb',
    providerType: 'bank',
  },
  {
    id: 'hdb',
    bankCode: 'HDB',
    bankName: 'Ngân hàng TMCP Phát triển TP.HCM',
    shortName: 'HDBank',
    color: '#ED1C24',
    apiEndpoint: 'https://sandbox.hdbank.com.vn/openapi',
    webhookUrl: 'https://taphoammo.vn/api/webhook/hdb',
    providerType: 'bank',
  },
  {
    id: 'scb',
    bankCode: 'SCB',
    bankName: 'Ngân hàng TMCP Sài Gòn',
    shortName: 'SCB',
    color: '#0054A6',
    apiEndpoint: 'https://api.scb.com.vn/payment',
    webhookUrl: 'https://taphoammo.vn/api/webhook/scb',
    providerType: 'bank',
  },
];

export const THIRD_PARTY_CATALOG: BankCatalogEntry[] = [
  {
    id: 'momo',
    bankCode: 'MOMO',
    bankName: 'Ví điện tử MoMo',
    shortName: 'MoMo',
    color: '#A50064',
    apiEndpoint: 'https://payment.momo.vn/v2/gateway/api',
    webhookUrl: 'https://taphoammo.vn/api/webhook/momo',
    providerType: 'third_party',
  },
  {
    id: 'zalopay',
    bankCode: 'ZLP',
    bankName: 'ZaloPay',
    shortName: 'ZaloPay',
    color: '#0068FF',
    apiEndpoint: 'https://openapi.zalopay.vn/v2/create',
    webhookUrl: 'https://taphoammo.vn/api/webhook/zalopay',
    providerType: 'third_party',
  },
  {
    id: 'vnpay',
    bankCode: 'VNP',
    bankName: 'Cổng thanh toán VNPay',
    shortName: 'VNPay',
    color: '#005BA3',
    apiEndpoint: 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html',
    webhookUrl: 'https://taphoammo.vn/api/webhook/vnpay',
    providerType: 'third_party',
  },
  {
    id: 'paypal',
    bankCode: 'PP',
    bankName: 'PayPal',
    shortName: 'PayPal',
    color: '#003087',
    apiEndpoint: 'https://api-m.paypal.com/v2/checkout/orders',
    webhookUrl: 'https://taphoammo.vn/api/webhook/paypal',
    providerType: 'third_party',
  },
  {
    id: 'stripe',
    bankCode: 'STR',
    bankName: 'Stripe',
    shortName: 'Stripe',
    color: '#635BFF',
    apiEndpoint: 'https://api.stripe.com/v1/checkout/sessions',
    webhookUrl: 'https://taphoammo.vn/api/webhook/stripe',
    providerType: 'third_party',
  },
  {
    id: 'sepay',
    bankCode: 'SEP',
    bankName: 'SePay — cổng QR & webhook',
    shortName: 'SePay',
    color: '#0D9488',
    apiEndpoint: 'https://my.sepay.vn/api/v1',
    webhookUrl: 'https://taphoammo.vn/api/webhook/sepay',
    providerType: 'third_party',
  },
];

export const initialTransactions: Transaction[] = [
  {
    id: 'GD001',
    username: 'minhnv',
    amount: 500_000,
    bank: 'Vietcombank',
    status: 'success',
    date: '17/05/2026 14:20',
    ref: 'VCB20260517001',
    content: 'NAP TIEN TAI KHOAN TAPHOAMMO MINHNV',
    note: 'Webhook xác nhận thành công — khớp mã đơn #ORD-8821',
  },
  {
    id: 'GD002',
    username: 'lan_tt',
    amount: 1_200_000,
    bank: 'Techcombank',
    status: 'pending',
    date: '17/05/2026 13:45',
    ref: 'TCB20260517002',
    content: 'CHUYEN KHOAN LAN TT NAP VI',
    note: 'Đang chờ ngân hàng xác nhận (timeout 15 phút)',
  },
  {
    id: 'GD003',
    username: 'hunglv',
    amount: 250_000,
    bank: 'MB Bank',
    status: 'failed',
    date: '17/05/2026 12:30',
    ref: 'MB20260517003',
    content: 'NAP TIEN HUNG LV',
    note: 'Lỗi: số tiền không khớp đơn hàng — từ chối tự động',
  },
  {
    id: 'GD004',
    username: 'phamha',
    amount: 3_500_000,
    bank: 'Vietcombank',
    status: 'success',
    date: '17/05/2026 11:15',
    ref: 'VCB20260517004',
    content: 'PHAM THU HA CHUYEN KHOAN',
    note: 'Đã ghi có vào ví người dùng',
  },
];

export function catalogToGateway(entry: BankCatalogEntry): PaymentGateway {
  const isUsd = entry.providerType === 'third_party' && (entry.id === 'paypal' || entry.id === 'stripe');
  return {
    ...entry,
    status: 'disconnected',
    environment: 'sandbox',
    merchantId: '',
    lastSync: '—',
    todayVolume: 0,
    enabled: false,
    minDepositAmount: isUsd ? 1 : DEFAULT_MIN_DEPOSIT_VND,
    minDepositCurrency: isUsd ? 'USD' : 'VND',
    depositNote: '',
    accountNumber: '',
    accountHolder: 'TAPHOAMMO VN',
    depositPromotionEnabled: true,
    depositPromotionTiers: getDefaultTiersForCurrency(isUsd ? 'USD' : 'VND'),
  };
}
